name: deploy-db
on:
  push:
    branches:
      - "main"
      - "staging"
  pull_request:
    type: [synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
          cache: "yarn"
      - run: yarn
      - name: Run production migration
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: yarn run db:deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_PROD }}
      - name: Run staging migration
        if: github.event_name == 'push' && github.ref == 'refs/heads/staging'
        run: yarn run db:deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_STAGING }}
      - name: Run dev migration
        if: github.event_name == 'pull_request'
        run: yarn run db:deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_DEV }}
